### ISSUE TITLE
build-llinux.sh

### ISSUE THREAD

**Issue by sk-5** [rickparrish/Gunshot#1]
What happened to this file?  in the readme it says it should be at src\build-linux.sh.

**Comment by rickparrish** [comment]
Started working on a new port recently, and didn't get as far as testing things on Linux yet.  I guess I probably re-used the README file though, hence why it still references that file.

**Comment by sk-5** [comment]
Ahh.  I'd be very interested in the updated port, when its ready-ish. :)  :+1:

**Comment by rickparrish** [comment]
Not sure I'll be working on it any more in the future.  I've heard that the alpha releases were still quite buggy, so even if I get it fully ported there is probably still a lot of bugfixing work that will need to take place, and since I'm not really familiar with the code base that sounds like more work than I'm interested in.

**Comment by sk-5** [comment]
Ahh gotcha.
